ARG A6T_CONTROLLER_BASE=gcr.io/ucdlib-pubreg/argonaut:latest
ARG NODE_BASE=gcr.io/ucdlib-pubreg/casita:latest

FROM ${NODE_BASE} as node-base

FROM ${A6T_CONTROLLER_BASE}

COPY --from=node-base /casita /casita
WORKDIR /casita
RUN npm link
RUN npm link @ucd-lib/casita-worker

ENV ARGONAUT_GRAPH=/casita/services/nodejs/a6t-controller/lib/graph.js