ARG NODE_VERSION=16

FROM node:${NODE_VERSION}

RUN apt-get update && apt-get install -y ssh

RUN mkdir /root/.ssh/
RUN touch /root/.ssh/known_hosts
RUN ssh-keyscan grb-box.cstars.ucdavis.edu >> /root/.ssh/known_hosts

RUN mkdir /casita
WORKDIR /casita

COPY package.json .
COPY package-lock.json .
RUN npm install --production
RUN npm install -g

COPY node-commons node-commons
COPY services services
COPY tasks tasks

ENV GRB_FILE ${GRB_FILE}
ENV SSH_KEY_USERNAME ${SSH_KEY_USERNAME}